services:
  rustapp:
    container_name: rustapp
    image: solulabimage/rustapp:1.0.0  # Docker image names should be lowercase
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres  # Add this line
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}